### PR TITLE
addin explicit stage for pull request

### PR DESCRIPTION
**Pull request by saroup**

### CODE REVIEW

**Review by in4margaret — DISMISSED** [review]

**Comment by in4margaret** [comment]
@saroup  yarn is running by default if we don't have install block

**Comment by in4margaret** [comment]
@saroup  we use standard.js (https://standardjs.com/) for linting and added it to package.json test to run it  to make sure we follow standards.

**Comment by in4margaret** [comment]
This closes #61 #62 #42

**Comment by in4margaret** [comment]
@saroup  We need "yarn build" twice because one is used to test that it can be built in 'test' stage and another one is used in deploy. Otherwise we would need to add data persistence between jobs as described in https://docs.travis-ci.com/user/build-stages/#Data-persistence-between-stages-and-jobs

**Comment by saroup** [comment]
Also closes #54

**Comment by in4margaret** [comment]
@saroup  We use cache for yarn to speed up installing of packages as they don't change often

**Review by in4margaret — APPROVED** [review]

**Comment by in4margaret** [comment]
fixes #54 #62 #61 #42

**Pull request merged**
